// FIFA 3-letter code → flag emoji (World Cup 2022 + 2026)
export const CODE_FLAGS: Record<string, string> = {
  ALG: '🇩🇿', ARG: '🇦🇷', AUS: '🇦🇺', AUT: '🇦🇹',
  BEL: '🇧🇪', BIH: '🇧🇦', BRA: '🇧🇷', CAN: '🇨🇦',
  CIV: '🇨🇮', CMR: '🇨🇲', COD: '🇨🇩', COL: '🇨🇴',
  CPV: '🇨🇻', CRC: '🇨🇷', CRO: '🇭🇷', CUW: '🇨🇼',
  CZE: '🇨🇿', DEN: '🇩🇰', ECU: '🇪🇨', EGY: '🇪🇬',
  ENG: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', ESP: '🇪🇸', FRA: '🇫🇷', FWC: '🏆',
  GER: '🇩🇪', GHA: '🇬🇭', HAI: '🇭🇹', IRN: '🇮🇷',
  IRQ: '🇮🇶', JOR: '🇯🇴', JPN: '🇯🇵', KOR: '🇰🇷',
  KSA: '🇸🇦', MAR: '🇲🇦', MEX: '🇲🇽', NED: '🇳🇱',
  NOR: '🇳🇴', NZL: '🇳🇿', PAN: '🇵🇦', PAR: '🇵🇾',
  POL: '🇵🇱', POR: '🇵🇹', QAT: '🇶🇦', RSA: '🇿🇦',
  SCO: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', SEN: '🇸🇳', SRB: '🇷🇸', SUI: '🇨🇭',
  SWE: '🇸🇪', TUN: '🇹🇳', TUR: '🇹🇷', URU: '🇺🇾',
  USA: '🇺🇸', UZB: '🇺🇿', WAL: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
}

// Full team name (as stored in DB) → flag emoji — covers all albums 2002–2026
const TEAM_FLAGS: Record<string, string> = {
  'Algeria':                '🇩🇿',
  'Angola':                 '🇦🇴',
  'Argentina':              '🇦🇷',
  'Australia':              '🇦🇺',
  'Austria':                '🇦🇹',
  'Belgium':                '🇧🇪',
  'Bosnia and Herzegovina': '🇧🇦',
  'Bosnia & Herzegovina':   '🇧🇦',
  'Brazil':                 '🇧🇷',
  'Cameroon':               '🇨🇲',
  'Canada':                 '🇨🇦',
  'Cape Verde':             '🇨🇻',
  'Chile':                  '🇨🇱',
  'China':                  '🇨🇳',
  'Colombia':               '🇨🇴',
  'Congo DR':               '🇨🇩',
  'Costa Rica':             '🇨🇷',
  'Croatia':                '🇭🇷',
  'Curaçao':                '🇨🇼',
  'Czech Republic':         '🇨🇿',
  'Czechia':                '🇨🇿',
  'Denmark':                '🇩🇰',
  'Ecuador':                '🇪🇨',
  'Egypt':                  '🇪🇬',
  'England':                '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'France':                 '🇫🇷',
  'Germany':                '🇩🇪',
  'Ghana':                  '🇬🇭',
  'Greece':                 '🇬🇷',
  'Haiti':                  '🇭🇹',
  'Honduras':               '🇭🇳',
  'Iceland':                '🇮🇸',
  'Iran':                   '🇮🇷',
  'Iraq':                   '🇮🇶',
  'Ireland':                '🇮🇪',
  'Italy':                  '🇮🇹',
  'Ivory Coast':            '🇨🇮',
  'Japan':                  '🇯🇵',
  'Jordan':                 '🇯🇴',
  'Korea DPR':              '🇰🇵',
  'Korea Republic':         '🇰🇷',
  'Mexico':                 '🇲🇽',
  'México':                 '🇲🇽',
  'Morocco':                '🇲🇦',
  'Netherlands':            '🇳🇱',
  'New Zealand':            '🇳🇿',
  'Nigeria':                '🇳🇬',
  'Norway':                 '🇳🇴',
  'Panama':                 '🇵🇦',
  'Paraguay':               '🇵🇾',
  'Peru':                   '🇵🇪',
  'Poland':                 '🇵🇱',
  'Portugal':               '🇵🇹',
  'Qatar':                  '🇶🇦',
  'Russia':                 '🇷🇺',
  'Saudi Arabia':           '🇸🇦',
  'Scotland':               '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Senegal':                '🇸🇳',
  'Serbia':                 '🇷🇸',
  'Serbia & Montenegro':    '🇷🇸',
  'Slovakia':               '🇸🇰',
  'Slovenia':               '🇸🇮',
  'South Africa':           '🇿🇦',
  'South Korea':            '🇰🇷',
  'Spain':                  '🇪🇸',
  'Sweden':                 '🇸🇪',
  'Switzerland':            '🇨🇭',
  'Togo':                   '🇹🇬',
  'Trinidad and Tobago':    '🇹🇹',
  'Tunisia':                '🇹🇳',
  'Turkey':                 '🇹🇷',
  'Türkiye':                '🇹🇷',
  'Ukraine':                '🇺🇦',
  'Uruguay':                '🇺🇾',
  'USA':                    '🇺🇸',
  'Uzbekistan':             '🇺🇿',
  'Wales':                  '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
}

export function teamFlag(team: string | null | undefined): string {
  if (!team) return ''
  return TEAM_FLAGS[team] ?? ''
}

// Album name (as stored in DB) → host country flag(s)
const ALBUM_FLAGS: Record<string, string> = {
  'Korea/Japan':  '🇰🇷🇯🇵',
  'Germany':      '🇩🇪',
  'South Africa': '🇿🇦',
  'Brazil':       '🇧🇷',
  'Russia':       '🇷🇺',
  'Qatar':        '🇶🇦',
  'USA/CAN/MEX':  '🇺🇸🇨🇦🇲🇽',
}

export function albumFlags(name: string): string {
  return ALBUM_FLAGS[name] ?? ''
}
